<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFrameworks>net10.0;net11.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsPackable>true</IsPackable>
		<Version>11.0.1-rc.0</Version>
		<Authors>Pieterjan De Clippel</Authors>
		<Company>MintPlayer</Company>
		<Product>MintPlayer.AspNetCore.Hsts</Product>
		<Description>Correct HSTS Middleware for ASP.NET Core.</Description>
		<PackageProjectUrl>https://github.com/MintPlayer/MintPlayer.AspNetCore.Tools/tree/master/Hsts/MintPlayer.AspNetCore.Hsts</PackageProjectUrl>
		<RepositoryUrl>https://github.com/MintPlayer/MintPlayer.AspNetCore.Tools</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageId>MintPlayer.AspNetCore.Hsts</PackageId>
		<PackageTags>ASP.NET;ASP.NET Core;HSTS;Strict-Transport-Security;Middleware;Security</PackageTags>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<!-- Include XML markups in the nupkg -->
	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>
	
</Project>
