using System.Globalization;
using System.Text.Encodings.Web;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.DependencyInjection;

namespace MintPlayer.AspNetCore.Endpoints;

/// <summary>
/// A link to one named endpoint: its route name, its route template and the values to put in it.
/// Returned by the generated <c>Routes</c> class, so a URL is built from typed arguments instead of
/// a magic string.
/// </summary>
/// <remarks>
/// <para>
/// <b>Why an object and not a string.</b> A bare string closes off everything that needs the name
/// or the values rather than the finished text — <c>CreatedAtRoute</c>, absolute URIs, a
/// <see cref="LinkGenerator"/> that honours <c>PathBase</c>. The implicit conversion to
/// <see cref="string"/> keeps the common case — <c>Results.Created(Routes.Api.Users.GetUser(id: 42), body)</c>
/// — compiling unchanged.
/// </para>
/// <para>
/// <b><see cref="Path(LinkGenerator)"/> delegates to ASP.NET Core; <see cref="ToString"/> cannot.</b>
/// <see cref="ToString"/> has no <see cref="LinkGenerator"/> to ask, so it substitutes into
/// <see cref="Template"/> itself, following routing's own <c>TemplateBinder</c> and
/// <c>UriBuildingContext</c> step for step and encoding with <see cref="UrlEncoder.Default"/> — the
/// encoder routing uses. That last point is load-bearing: an earlier substitution helper built on
/// <see cref="Uri.EscapeDataString(string)"/> matched on 12 cases and diverged on 7 of 16 once
/// <c>! $ ( ) * , ; @</c> were included, all of which <see cref="UrlEncoder.Default"/> leaves alone.
/// A test builds a real <see cref="LinkGenerator"/> and asserts the two agree byte for byte. The
/// substitution lives in <see cref="EndpointTemplateBinder"/>, whose source the typed-client generator
/// also emits into client projects, so a generated client builds the same URL this does.
/// </para>
/// <para>
/// What <see cref="ToString"/> cannot see, and <see cref="Path(LinkGenerator)"/> can: route
/// constraints (<c>{id:int}</c> given <c>"abc"</c> makes <see cref="LinkGenerator"/> fail, while
/// <see cref="ToString"/> substitutes it), <c>RouteOptions.LowercaseUrls</c>,
/// <c>LowercaseQueryStrings</c> and <c>AppendTrailingSlash</c>, outbound parameter transformers,
/// and a <see cref="UrlEncoder"/> replaced in the container through <c>WebEncoderOptions</c>. An
/// application that uses any of those should call <see cref="Path(HttpContext)"/>.
/// </para>
/// </remarks>
public sealed class EndpointRoute
{
    /// <summary>Creates a link to the endpoint named <paramref name="name"/>.</summary>
    /// <param name="name">The endpoint's route name — what the generated mapping passes to <c>WithName</c>.</param>
    /// <param name="template">The endpoint's full route template, group prefixes included.</param>
    /// <param name="values">The route values, plus any values that belong in the query string.</param>
    public EndpointRoute(string name, string template, RouteValueDictionary values)
    {
        ArgumentNullException.ThrowIfNull(name);
        ArgumentNullException.ThrowIfNull(template);
        ArgumentNullException.ThrowIfNull(values);

        Name = name;
        Template = template;
        Values = values;
    }

    /// <summary>The endpoint's route name, which is also its OpenAPI <c>operationId</c>.</summary>
    public string Name { get; }

    /// <summary>The composed route template, e.g. <c>/api/users/{id}</c>.</summary>
    public string Template { get; }

    /// <summary>
    /// The values: one per route token that has one, then the query values that are not null.
    /// Anything that is not a token of <see cref="Template"/> ends up in the query string.
    /// </summary>
    public RouteValueDictionary Values { get; }

    /// <summary>
    /// The path, generated by ASP.NET Core's own <see cref="LinkGenerator"/> from <see cref="Name"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">
    /// <see cref="LinkGenerator"/> could not generate the link. It reports that by returning
    /// <see langword="null"/> — for an unknown name, a missing required value or a constraint the
    /// value violates — and a null URL passed on is worse than an exception here.
    /// </exception>
    public string Path(LinkGenerator links)
    {
        ArgumentNullException.ThrowIfNull(links);

        return links.GetPathByName(Name, Values) ?? throw GenerationFailed();
    }

    /// <summary>
    /// The path, generated by the request's <see cref="LinkGenerator"/> and prefixed with its
    /// <see cref="HttpRequest.PathBase"/>.
    /// </summary>
    /// <remarks>
    /// Deliberately not <c>GetPathByName(HttpContext, …)</c>: that overload also takes the current
    /// request's route values as ambient values, which can fill a token this link left out — so the
    /// same <see cref="EndpointRoute"/> would produce different URLs on different pages. Only the
    /// path base is taken from the request.
    /// </remarks>
    /// <exception cref="InvalidOperationException">See <see cref="Path(LinkGenerator)"/>.</exception>
    public string Path(HttpContext httpContext)
    {
        ArgumentNullException.ThrowIfNull(httpContext);

        var links = httpContext.RequestServices.GetRequiredService<LinkGenerator>();
        return links.GetPathByName(Name, Values, httpContext.Request.PathBase) ?? throw GenerationFailed();
    }

    /// <summary>
    /// The absolute URI, using the request's scheme, host and path base.
    /// </summary>
    /// <remarks>
    /// The request's host is taken as given. Behind a proxy it is only trustworthy once forwarded
    /// headers are processed and host filtering is configured — see the
    /// <see cref="LinkGenerator"/> security remarks.
    /// </remarks>
    /// <exception cref="InvalidOperationException">See <see cref="Path(LinkGenerator)"/>.</exception>
    public string Uri(HttpContext httpContext)
    {
        ArgumentNullException.ThrowIfNull(httpContext);

        var links = httpContext.RequestServices.GetRequiredService<LinkGenerator>();
        var request = httpContext.Request;
        return links.GetUriByName(Name, Values, request.Scheme, request.Host, request.PathBase) ?? throw GenerationFailed();
    }

    /// <summary>
    /// The path, substituted into <see cref="Template"/> exactly as <see cref="LinkGenerator"/> would
    /// with default routing options, without needing one.
    /// </summary>
    /// <exception cref="InvalidOperationException">
    /// A required token has no value, or an empty one — the cases where <see cref="LinkGenerator"/>
    /// returns <see langword="null"/>. There is no correct string to return instead.
    /// </exception>
    public override string ToString() =>
        EndpointTemplateBinder.Bind(Template, Values) ?? throw GenerationFailed();

    /// <summary>Converts the link to its path, as <see cref="ToString"/>.</summary>
    public static implicit operator string(EndpointRoute route)
    {
        ArgumentNullException.ThrowIfNull(route);
        return route.ToString();
    }

    private InvalidOperationException GenerationFailed()
    {
        var supplied = Values.Count == 0
            ? "no values"
            : string.Join(", ", Values.Select(pair => $"{pair.Key} = '{Convert.ToString(pair.Value, CultureInfo.InvariantCulture)}'"));

        return new InvalidOperationException(
            $"No URL could be generated for endpoint '{Name}' ({Template}) from {supplied}. " +
            "A required route value is missing or empty, a value violates a route constraint, " +
            "or no endpoint is registered under that name.");
    }
}
