using System.Collections;
using System.Globalization;
using System.Text;
using System.Text.Encodings.Web;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.DependencyInjection;

namespace MintPlayer.AspNetCore.Endpoints;

/// <summary>
/// A link to one named endpoint: its route name, its route template and the values to put in it.
/// Returned by the generated <c>Routes</c> class, so a URL is built from typed arguments instead of
/// a magic string.
/// </summary>
/// <remarks>
/// <para>
/// <b>Why an object and not a string.</b> A bare string closes off everything that needs the name
/// or the values rather than the finished text — <c>CreatedAtRoute</c>, absolute URIs, a
/// <see cref="LinkGenerator"/> that honours <c>PathBase</c>. The implicit conversion to
/// <see cref="string"/> keeps the common case — <c>Results.Created(Routes.Api.Users.GetUser(id: 42), body)</c>
/// — compiling unchanged.
/// </para>
/// <para>
/// <b><see cref="Path(LinkGenerator)"/> delegates to ASP.NET Core; <see cref="ToString"/> cannot.</b>
/// <see cref="ToString"/> has no <see cref="LinkGenerator"/> to ask, so it substitutes into
/// <see cref="Template"/> itself, following routing's own <c>TemplateBinder</c> and
/// <c>UriBuildingContext</c> step for step and encoding with <see cref="UrlEncoder.Default"/> — the
/// encoder routing uses. That last point is load-bearing: an earlier substitution helper built on
/// <see cref="Uri.EscapeDataString(string)"/> matched on 12 cases and diverged on 7 of 16 once
/// <c>! $ ( ) * , ; @</c> were included, all of which <see cref="UrlEncoder.Default"/> leaves alone.
/// A test builds a real <see cref="LinkGenerator"/> and asserts the two agree byte for byte.
/// </para>
/// <para>
/// What <see cref="ToString"/> cannot see, and <see cref="Path(LinkGenerator)"/> can: route
/// constraints (<c>{id:int}</c> given <c>"abc"</c> makes <see cref="LinkGenerator"/> fail, while
/// <see cref="ToString"/> substitutes it), <c>RouteOptions.LowercaseUrls</c>,
/// <c>LowercaseQueryStrings</c> and <c>AppendTrailingSlash</c>, outbound parameter transformers,
/// and a <see cref="UrlEncoder"/> replaced in the container through <c>WebEncoderOptions</c>. An
/// application that uses any of those should call <see cref="Path(HttpContext)"/>.
/// </para>
/// </remarks>
public sealed class EndpointRoute
{
    /// <summary>Creates a link to the endpoint named <paramref name="name"/>.</summary>
    /// <param name="name">The endpoint's route name — what the generated mapping passes to <c>WithName</c>.</param>
    /// <param name="template">The endpoint's full route template, group prefixes included.</param>
    /// <param name="values">The route values, plus any values that belong in the query string.</param>
    public EndpointRoute(string name, string template, RouteValueDictionary values)
    {
        ArgumentNullException.ThrowIfNull(name);
        ArgumentNullException.ThrowIfNull(template);
        ArgumentNullException.ThrowIfNull(values);

        Name = name;
        Template = template;
        Values = values;
    }

    /// <summary>The endpoint's route name, which is also its OpenAPI <c>operationId</c>.</summary>
    public string Name { get; }

    /// <summary>The composed route template, e.g. <c>/api/users/{id}</c>.</summary>
    public string Template { get; }

    /// <summary>
    /// The values: one per route token that has one, then the query values that are not null.
    /// Anything that is not a token of <see cref="Template"/> ends up in the query string.
    /// </summary>
    public RouteValueDictionary Values { get; }

    /// <summary>
    /// The path, generated by ASP.NET Core's own <see cref="LinkGenerator"/> from <see cref="Name"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">
    /// <see cref="LinkGenerator"/> could not generate the link. It reports that by returning
    /// <see langword="null"/> — for an unknown name, a missing required value or a constraint the
    /// value violates — and a null URL passed on is worse than an exception here.
    /// </exception>
    public string Path(LinkGenerator links)
    {
        ArgumentNullException.ThrowIfNull(links);

        return links.GetPathByName(Name, Values) ?? throw GenerationFailed();
    }

    /// <summary>
    /// The path, generated by the request's <see cref="LinkGenerator"/> and prefixed with its
    /// <see cref="HttpRequest.PathBase"/>.
    /// </summary>
    /// <remarks>
    /// Deliberately not <c>GetPathByName(HttpContext, …)</c>: that overload also takes the current
    /// request's route values as ambient values, which can fill a token this link left out — so the
    /// same <see cref="EndpointRoute"/> would produce different URLs on different pages. Only the
    /// path base is taken from the request.
    /// </remarks>
    /// <exception cref="InvalidOperationException">See <see cref="Path(LinkGenerator)"/>.</exception>
    public string Path(HttpContext httpContext)
    {
        ArgumentNullException.ThrowIfNull(httpContext);

        var links = httpContext.RequestServices.GetRequiredService<LinkGenerator>();
        return links.GetPathByName(Name, Values, httpContext.Request.PathBase) ?? throw GenerationFailed();
    }

    /// <summary>
    /// The absolute URI, using the request's scheme, host and path base.
    /// </summary>
    /// <remarks>
    /// The request's host is taken as given. Behind a proxy it is only trustworthy once forwarded
    /// headers are processed and host filtering is configured — see the
    /// <see cref="LinkGenerator"/> security remarks.
    /// </remarks>
    /// <exception cref="InvalidOperationException">See <see cref="Path(LinkGenerator)"/>.</exception>
    public string Uri(HttpContext httpContext)
    {
        ArgumentNullException.ThrowIfNull(httpContext);

        var links = httpContext.RequestServices.GetRequiredService<LinkGenerator>();
        var request = httpContext.Request;
        return links.GetUriByName(Name, Values, request.Scheme, request.Host, request.PathBase) ?? throw GenerationFailed();
    }

    /// <summary>
    /// The path, substituted into <see cref="Template"/> exactly as <see cref="LinkGenerator"/> would
    /// with default routing options, without needing one.
    /// </summary>
    /// <exception cref="InvalidOperationException">
    /// A required token has no value, or an empty one — the cases where <see cref="LinkGenerator"/>
    /// returns <see langword="null"/>. There is no correct string to return instead.
    /// </exception>
    public override string ToString() =>
        TemplateSubstitution.Bind(Template, Values) ?? throw GenerationFailed();

    /// <summary>Converts the link to its path, as <see cref="ToString"/>.</summary>
    public static implicit operator string(EndpointRoute route)
    {
        ArgumentNullException.ThrowIfNull(route);
        return route.ToString();
    }

    private InvalidOperationException GenerationFailed()
    {
        var supplied = Values.Count == 0
            ? "no values"
            : string.Join(", ", Values.Select(pair => $"{pair.Key} = '{Convert.ToString(pair.Value, CultureInfo.InvariantCulture)}'"));

        return new InvalidOperationException(
            $"No URL could be generated for endpoint '{Name}' ({Template}) from {supplied}. " +
            "A required route value is missing or empty, a value violates a route constraint, " +
            "or no endpoint is registered under that name.");
    }

    /// <summary>
    /// A port of the parts of ASP.NET Core's <c>TemplateBinder</c> and <c>UriBuildingContext</c>
    /// that apply to a named link with no ambient values.
    /// </summary>
    /// <remarks>
    /// Kept structurally identical to the originals — the segment/buffer state machine included —
    /// rather than rewritten "more simply", because each odd-looking rule is observable: a trailing
    /// value equal to its default is dropped, an omitted optional token takes its slash with it, a
    /// <c>{id}.{format?}</c> drops the dot, a <c>{**path}</c> keeps its slashes and a
    /// <c>{*path}</c> escapes them, and a value compared with a default is compared as routing
    /// compares it (strings case-insensitively, anything else by <see cref="object.Equals(object)"/>).
    /// </remarks>
    private static class TemplateSubstitution
    {
        public static string? Bind(string template, RouteValueDictionary values)
        {
            var segments = Parse(template);
            if (segments is null) return null;

            var parameters = segments.SelectMany(segment => segment).Where(part => part.IsParameter).ToList();
            var parameterNames = new HashSet<string>(parameters.Select(parameter => parameter.Name), StringComparer.OrdinalIgnoreCase);
            var defaults = new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase);
            foreach (var parameter in parameters)
            {
                if (parameter.Default is not null)
                    defaults[parameter.Name] = parameter.Default;
            }

            // TemplateBinder.GetValues, with no ambient values and no filters.
            var accepted = new RouteValueDictionary();
            foreach (var parameter in parameters)
            {
                if (accepted.ContainsKey(parameter.Name)) continue;

                if (values.TryGetValue(parameter.Name, out var value) && IsNonEmpty(value))
                    accepted[parameter.Name] = value;
                else if (parameter.IsOptional || parameter.IsCatchAll)
                    continue;
                else if (parameter.Default is not null)
                    accepted[parameter.Name] = parameter.Default;
                else
                    return null;
            }

            foreach (var pair in values)
            {
                if (!defaults.ContainsKey(pair.Key) && !accepted.ContainsKey(pair.Key) && !parameterNames.Contains(pair.Key))
                    accepted.Add(pair.Key, pair.Value);
            }

            // TemplateBinder.TryBindValuesCore.
            var context = new UriBuilder();
            foreach (var segment in segments)
            {
                for (var j = 0; j < segment.Count; j++)
                {
                    var part = segment[j];
                    if (part.IsLiteral || part.IsSeparator)
                    {
                        if (!context.Accept(part.Text, encodeSlashes: true)) return null;
                        continue;
                    }

                    accepted.Remove(part.Name, out var value);

                    var isSameAsDefault = defaults.TryGetValue(part.Name, out var defaultValue) && RoutePartsEqual(value, defaultValue);
                    var converted = Convert.ToString(value, CultureInfo.InvariantCulture);

                    if (isSameAsDefault)
                    {
                        if (!context.Buffer(converted)) return null;
                    }
                    else if (!context.Accept(converted, part.EncodeSlashes))
                    {
                        if (j != 0 && part.IsOptional && segment[j - 1].IsSeparator)
                            context.Remove();
                        else
                            return null;
                    }
                }

                context.EndSegment();
            }

            var query = new StringBuilder();
            foreach (var pair in accepted)
            {
                if (defaults.ContainsKey(pair.Key)) continue;

                if (pair.Value is IEnumerable sequence and not string)
                {
                    foreach (var item in sequence)
                        AppendQuery(query, pair.Key, item);
                }
                else
                {
                    AppendQuery(query, pair.Key, pair.Value);
                }
            }

            // UriHelper.BuildRelative: an empty path is "/".
            var path = context.Path;
            if (path.Length > 0 && path[0] != '/') path = "/" + path;
            if (path.Length == 0) path = "/";

            return path + query;
        }

        private static void AppendQuery(StringBuilder query, string key, object? value)
        {
            var converted = Convert.ToString(value, CultureInfo.InvariantCulture);
            if (string.IsNullOrEmpty(converted)) return;

            query.Append(query.Length == 0 ? '?' : '&');
            query.Append(UrlEncoder.Default.Encode(key));
            query.Append('=');
            query.Append(UrlEncoder.Default.Encode(converted));
        }

        private static bool IsNonEmpty(object? value) => value is not null && value is not "";

        private static bool RoutePartsEqual(object? a, object? b)
        {
            var sa = a as string;
            var sb = b as string;

            if ((sa == "" && sb is null) || (sb == "" && sa is null))
                return true;
            if (sa is not null && sb is not null)
                return string.Equals(sa, sb, StringComparison.OrdinalIgnoreCase);
            if (a is not null && b is not null)
                return a.Equals(b);
            return a == b;
        }

        /// <summary>
        /// Splits a template into segments of parts. Returns null for a template this port does not
        /// understand, rather than guessing.
        /// </summary>
        private static List<List<Part>>? Parse(string template)
        {
            if (template.StartsWith("~/", StringComparison.Ordinal)) template = template.Substring(1);

            var segments = new List<List<Part>>();
            var current = new List<Part>();
            var literal = new StringBuilder();

            void FlushLiteral()
            {
                if (literal.Length == 0) return;
                current.Add(Part.Literal(literal.ToString()));
                literal.Clear();
            }

            void EndSegment()
            {
                FlushLiteral();
                if (current.Count > 0) segments.Add(current);
                current = new List<Part>();
            }

            for (var i = 0; i < template.Length; i++)
            {
                var c = template[i];

                if (c == '/')
                {
                    EndSegment();
                }
                else if (c == '{' && i + 1 < template.Length && template[i + 1] == '{')
                {
                    literal.Append('{');
                    i++;
                }
                else if (c == '}' && i + 1 < template.Length && template[i + 1] == '}')
                {
                    literal.Append('}');
                    i++;
                }
                else if (c == '{')
                {
                    // The body ends at the first '}' that is not doubled; "}}" inside a parameter is an
                    // escaped brace belonging to a regex constraint.
                    var body = new StringBuilder();
                    var closed = false;
                    for (i++; i < template.Length; i++)
                    {
                        if (template[i] == '}')
                        {
                            if (i + 1 < template.Length && template[i + 1] == '}')
                            {
                                body.Append('}');
                                i++;
                                continue;
                            }

                            closed = true;
                            break;
                        }

                        body.Append(template[i]);
                    }

                    if (!closed) return null;

                    FlushLiteral();
                    current.Add(Part.Parameter(body.ToString()));
                }
                else
                {
                    literal.Append(c);
                }
            }

            EndSegment();

            // RoutePatternParser turns the '.' before a trailing optional parameter into a separator.
            foreach (var segment in segments)
            {
                var last = segment.Count - 1;
                if (last > 0 && segment[last].IsOptional && segment[last - 1] is { IsLiteral: true, Text: "." })
                    segment[last - 1] = Part.Separator(".");
            }

            return segments;
        }

        private sealed class Part
        {
            private Part() { }

            public bool IsLiteral { get; private init; }
            public bool IsSeparator { get; private init; }
            public bool IsParameter { get; private init; }
            public string Text { get; private init; } = "";
            public string Name { get; private init; } = "";
            public bool IsOptional { get; private init; }
            public bool IsCatchAll { get; private init; }
            public bool EncodeSlashes { get; private init; } = true;
            public string? Default { get; private init; }

            public static Part Literal(string text) => new() { IsLiteral = true, Text = text };
            public static Part Separator(string text) => new() { IsSeparator = true, Text = text };

            public static Part Parameter(string body)
            {
                var catchAll = body.StartsWith('*');
                var encodeSlashes = !body.StartsWith("**", StringComparison.Ordinal);
                body = body.TrimStart('*');

                var nameEnd = body.IndexOfAny([':', '=', '?']);
                var name = nameEnd < 0 ? body : body.Substring(0, nameEnd);
                var rest = nameEnd < 0 ? "" : body.Substring(nameEnd);

                // A default is the text after the first '=' outside a constraint's argument list; an
                // optional marker is a trailing '?' outside one.
                string? defaultValue = null;
                var optional = false;
                var depth = 0;
                for (var i = 0; i < rest.Length; i++)
                {
                    var c = rest[i];
                    if (c == '(') depth++;
                    else if (c == ')' && depth > 0) depth--;
                    else if (c == '=' && depth == 0)
                    {
                        defaultValue = rest.Substring(i + 1);
                        break;
                    }
                    else if (c == '?' && depth == 0 && i == rest.Length - 1)
                    {
                        optional = true;
                    }
                }

                return new Part
                {
                    IsParameter = true,
                    Name = name,
                    IsOptional = optional,
                    IsCatchAll = catchAll,
                    EncodeSlashes = encodeSlashes,
                    Default = defaultValue,
                };
            }
        }

        /// <summary>A port of <c>UriBuildingContext</c>'s path half, with default options.</summary>
        private sealed class UriBuilder
        {
            private readonly StringBuilder path = new();
            private readonly List<(string Value, bool RequiresEncoding)> buffer = [];
            private bool uriInside;
            private bool bufferInside;
            private bool hasEmptySegment;
            private int lastValueOffset = -1;

            public string Path => path.ToString();

            public bool Accept(string? value, bool encodeSlashes)
            {
                if (string.IsNullOrEmpty(value))
                {
                    if (uriInside || bufferInside) return false;

                    hasEmptySegment = true;
                    return true;
                }

                if (hasEmptySegment) return false;

                foreach (var (buffered, requiresEncoding) in buffer)
                {
                    if (requiresEncoding) Encode(buffered, encodeSlashes: true);
                    else path.Append(buffered);
                }
                buffer.Clear();

                if (!uriInside && !bufferInside && path.Length != 0)
                    path.Append('/');

                bufferInside = true;
                uriInside = true;
                lastValueOffset = path.Length;

                // The first segment may carry a leading slash, which is not encoded.
                if (path.Length == 0 && value[0] == '/')
                {
                    path.Append('/');
                    Encode(value.Substring(1), encodeSlashes);
                }
                else
                {
                    Encode(value, encodeSlashes);
                }

                return true;
            }

            public bool Buffer(string? value)
            {
                if (string.IsNullOrEmpty(value))
                {
                    if (bufferInside) return false;

                    hasEmptySegment = true;
                    return true;
                }

                if (hasEmptySegment) return false;

                if (uriInside) return Accept(value, encodeSlashes: true);

                if (!bufferInside)
                {
                    if (path.Length != 0 || buffer.Count != 0)
                        buffer.Add(("/", false));
                    bufferInside = true;
                }

                buffer.Add((value, true));
                return true;
            }

            public void Remove()
            {
                path.Length = lastValueOffset;
                lastValueOffset = -1;
            }

            public void EndSegment()
            {
                bufferInside = false;
                uriInside = false;
            }

            private void Encode(string value, bool encodeSlashes)
            {
                if (encodeSlashes)
                {
                    path.Append(UrlEncoder.Default.Encode(value));
                    return;
                }

                var pieces = value.Split('/');
                for (var i = 0; i < pieces.Length; i++)
                {
                    if (i > 0) path.Append('/');
                    path.Append(UrlEncoder.Default.Encode(pieces[i]));
                }
            }
        }
    }
}
