using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace MintPlayer.AspNetCore.Endpoints.Generator;

internal static class Emitter
{
    public static string EmitPartialClass(EndpointInfo endpoint)
    {
        var baseClass = endpoint.GetBaseClassName();
        if (baseClass is null) return string.Empty;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(endpoint.Namespace))
        {
            sb.AppendLine($"namespace {endpoint.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {endpoint.ClassName} : {baseClass}");
        sb.AppendLine("{");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string EmitMappingExtension(AssemblyInfo assemblyInfo, ImmutableArray<EndpointInfo> endpoints)
    {
        // Filter to only valid endpoints (skip those with errors)
        var validEndpoints = endpoints
            .Where(e => !e.HasMultipleGroups)
            .Distinct()
            .ToList();

        if (validEndpoints.Count == 0) return string.Empty;

        var methodName = assemblyInfo.GetMethodName();
        var className = assemblyInfo.GetSafeClassName();
        var metadataClassName = assemblyInfo.GetMetadataClassName();

        // Group endpoints by their group association
        var ungrouped = validEndpoints.Where(e => e.GroupTypeFqn is null).ToList();
        var grouped = validEndpoints
            .Where(e => e.GroupTypeFqn is not null)
            .GroupBy(e => e.GroupTypeFqn!)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace MintPlayer.AspNetCore.Endpoints;");
        sb.AppendLine();
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        // Emit factory fields
        foreach (var endpoint in validEndpoints)
        {
            var fieldName = GetFactoryFieldName(endpoint);
            sb.AppendLine($"    private static readonly global::System.Func<global::System.IServiceProvider, object?[]?, {endpoint.FullyQualifiedName}> {fieldName} =");
            sb.AppendLine($"        global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateFactory<{endpoint.FullyQualifiedName}>(global::System.Type.EmptyTypes);");
            sb.AppendLine();
        }

        // Emit mapping method
        sb.AppendLine($"    public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder {methodName}(");
        sb.AppendLine($"        this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)");
        sb.AppendLine("    {");

        // Ungrouped endpoints
        foreach (var endpoint in ungrouped)
        {
            var fieldName = GetFactoryFieldName(endpoint);
            if (endpoint.Level == EndpointLevel.TypedWithResponse)
            {
                sb.AppendLine("        {");
                sb.AppendLine($"            var builder = MapEndpoint<{endpoint.FullyQualifiedName}>(app, {fieldName});");
                sb.AppendLine($"            AddProduces<{endpoint.FullyQualifiedName}, {endpoint.RequestTypeFqn}, {endpoint.ResponseTypeFqn}>(builder);");
                sb.AppendLine("        }");
            }
            else
            {
                sb.AppendLine($"        MapEndpoint<{endpoint.FullyQualifiedName}>(app, {fieldName});");
            }
            sb.AppendLine();
        }

        // Grouped endpoints
        foreach (var group in grouped)
        {
            sb.AppendLine($"        // Group: {group.Key}");
            sb.AppendLine("        {");
            sb.AppendLine($"            var group = MapGroup<{group.Key}>(app);");
            sb.AppendLine();

            foreach (var endpoint in group)
            {
                var fieldName = GetFactoryFieldName(endpoint);
                if (endpoint.Level == EndpointLevel.TypedWithResponse)
                {
                    sb.AppendLine("            {");
                    sb.AppendLine($"                var builder = MapEndpoint<{endpoint.FullyQualifiedName}>(group, {fieldName});");
                    sb.AppendLine($"                AddProduces<{endpoint.FullyQualifiedName}, {endpoint.RequestTypeFqn}, {endpoint.ResponseTypeFqn}>(builder);");
                    sb.AppendLine("            }");
                }
                else
                {
                    sb.AppendLine($"            MapEndpoint<{endpoint.FullyQualifiedName}>(group, {fieldName});");
                }
                sb.AppendLine();
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("        return app;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Emit helper methods
        EmitHelperMethods(sb);

        // Emit metadata property inside the extensions class
        EmitMetadataProperty(sb, validEndpoints);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitHelperMethods(StringBuilder sb)
    {
        // MapEndpoint<TEndpoint>
        sb.AppendLine("    private static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapEndpoint<TEndpoint>(");
        sb.AppendLine("        global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder routes,");
        sb.AppendLine("        global::System.Func<global::System.IServiceProvider, object?[]?, TEndpoint> factory)");
        sb.AppendLine("        where TEndpoint : class, global::MintPlayer.AspNetCore.Endpoints.IEndpoint");
        sb.AppendLine("    {");
        sb.AppendLine("        var builder = routes.MapMethods(");
        sb.AppendLine("            TEndpoint.Path,");
        sb.AppendLine("            TEndpoint.Methods,");
        sb.AppendLine("            async (global::Microsoft.AspNetCore.Http.HttpContext ctx) =>");
        sb.AppendLine("            {");
        sb.AppendLine("                var endpoint = factory(ctx.RequestServices, null);");
        sb.AppendLine("                try");
        sb.AppendLine("                {");
        sb.AppendLine("                    return await endpoint.HandleAsync(ctx);");
        sb.AppendLine("                }");
        sb.AppendLine("                finally");
        sb.AppendLine("                {");
        sb.AppendLine("                    await DisposeEndpointAsync(endpoint);");
        sb.AppendLine("                }");
        sb.AppendLine("            });");
        sb.AppendLine();
        sb.AppendLine("        builder.WithMetadata(typeof(TEndpoint).GetCustomAttributes(true));");
        sb.AppendLine("        TEndpoint.Configure(builder);");
        sb.AppendLine();
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // MapGroup<TGroup>
        sb.AppendLine("    private static global::Microsoft.AspNetCore.Routing.RouteGroupBuilder MapGroup<TGroup>(");
        sb.AppendLine("        global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder routes)");
        sb.AppendLine("        where TGroup : global::MintPlayer.AspNetCore.Endpoints.IEndpointGroup");
        sb.AppendLine("    {");
        sb.AppendLine("        var group = routes.MapGroup(TGroup.Prefix);");
        sb.AppendLine("        TGroup.Configure(group);");
        sb.AppendLine("        return group;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // AddProduces<TEndpoint, TRequest, TResponse>
        sb.AppendLine("    private static void AddProduces<TEndpoint, TRequest, TResponse>(");
        sb.AppendLine("        global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)");
        sb.AppendLine("        where TEndpoint : global::MintPlayer.AspNetCore.Endpoints.IEndpoint<TRequest, TResponse>");
        sb.AppendLine("    {");
        sb.AppendLine("        builder.Produces<TResponse>(TEndpoint.SuccessStatusCode);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // DisposeEndpointAsync
        sb.AppendLine("    private static async global::System.Threading.Tasks.ValueTask DisposeEndpointAsync(object endpoint)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (endpoint is global::System.IAsyncDisposable asyncDisposable)");
        sb.AppendLine("            await asyncDisposable.DisposeAsync();");
        sb.AppendLine("        else if (endpoint is global::System.IDisposable disposable)");
        sb.AppendLine("            disposable.Dispose();");
        sb.AppendLine("    }");
        sb.AppendLine();

        // CreateDescriptor<TEndpoint>
        sb.AppendLine("    private static global::MintPlayer.AspNetCore.Endpoints.EndpointDescriptor CreateDescriptor<TEndpoint>(string name)");
        sb.AppendLine("        where TEndpoint : global::MintPlayer.AspNetCore.Endpoints.IEndpointBase");
        sb.AppendLine("    {");
        sb.AppendLine("        return new(name, TEndpoint.Path, TEndpoint.Methods, typeof(TEndpoint));");
        sb.AppendLine("    }");
    }

    private static void EmitMetadataProperty(StringBuilder sb, List<EndpointInfo> endpoints)
    {
        sb.AppendLine("    public static global::System.Collections.Generic.IReadOnlyList<global::MintPlayer.AspNetCore.Endpoints.EndpointDescriptor> Endpoints { get; } =");
        sb.AppendLine("    [");
        foreach (var endpoint in endpoints)
        {
            sb.AppendLine($"        CreateDescriptor<{endpoint.FullyQualifiedName}>(\"{endpoint.ClassName}\"),");
        }
        sb.AppendLine("    ];");
        sb.AppendLine();
    }

    private static string GetFactoryFieldName(EndpointInfo endpoint)
    {
        // Use a sanitized version of the class name to avoid collisions
        var safeName = endpoint.FullyQualifiedName
            .Replace("global::", "")
            .Replace(".", "_");
        return $"_factory_{safeName}";
    }
}
