using System.CodeDom.Compiler;
using Microsoft.CodeAnalysis.CSharp;

namespace MintPlayer.AspNetCore.Endpoints.Generator;

/// <summary>
/// Writes the typed client files: one class per server assembly, and the shared URL helper.
/// </summary>
/// <remarks>
/// Same rules as every other generated file here: no <c>using</c> directives (the one
/// <c>global using</c> is the call-site convenience the mapping file also emits), every type
/// <c>global::</c>-qualified, extension methods called in their static form, and a <c>using</c>
/// <i>statement</i> avoided too, in favour of <c>try</c>/<c>finally</c>.
/// </remarks>
internal static class EndpointClientWriter
{
    public const string UrlHelperFileName = "EndpointClientUrl.g.cs";

    private const string ResourceName = "MintPlayer.AspNetCore.Endpoints.Generator.EndpointTemplateBinder.cs";
    private const string SourceNamespaceLine = "namespace MintPlayer.AspNetCore.Endpoints";
    private const string Namespace = EndpointsProducer.GeneratedNamespace;
    private const string Binder = "global::" + Namespace + ".EndpointTemplateBinder";
    private const string Pair = "global::System.Collections.Generic.KeyValuePair<string, object?>";

    private const string Header =
        "// <auto-generated/>\r\n" +
        "// Generated by MintPlayer.AspNetCore.Endpoints.Generator. Do not edit; changes are lost on the next build.";

    private static readonly Lazy<string> urlHelper = new(LoadUrlHelper);

    /// <summary>
    /// The runtime library's <c>EndpointTemplateBinder.cs</c>, embedded in this assembly at build time,
    /// with its namespace moved into the generated one.
    /// </summary>
    /// <remarks>
    /// The same text <c>EndpointRoute.ToString()</c> compiles, so a client URL and a server-side link
    /// cannot drift apart, and the byte-for-byte battery against <c>LinkGenerator</c> covers both. A
    /// missing resource or namespace line throws: Roslyn reports that as CS8785 naming this generator,
    /// and the generator tests fail on it, which beats a client that quietly builds URLs differently.
    /// </remarks>
    public static string UrlHelperSource() => urlHelper.Value;

    private static string LoadUrlHelper()
    {
        using var stream = typeof(EndpointClientWriter).Assembly.GetManifestResourceStream(ResourceName)
            ?? throw new InvalidOperationException($"The embedded resource '{ResourceName}' is missing from the generator assembly.");
        using var reader = new StreamReader(stream);
        var source = reader.ReadToEnd();

        var lines = source.Replace("\r\n", "\n").Split('\n');
        var index = Array.FindIndex(lines, line => line.TrimEnd() == SourceNamespaceLine);
        if (index < 0)
            throw new InvalidOperationException($"The embedded '{ResourceName}' has no '{SourceNamespaceLine}' line to move into '{Namespace}'.");

        lines[index] = "namespace " + Namespace;
        return Header + "\r\n" + string.Join("\r\n", lines);
    }

    /// <summary>
    /// A class name per server assembly: its last dotted segment plus <c>Client</c>
    /// (<c>MyShop.Api</c> → <c>ApiClient</c>), or the whole name when two assemblies would share one.
    /// </summary>
    public static List<string> ClassNames(List<string> assemblyNames)
    {
        var shortNames = assemblyNames.Select(name => Identifier(LastSegment(name)) + "Client").ToList();
        var result = new List<string>(assemblyNames.Count);
        var taken = new HashSet<string>(StringComparer.Ordinal);

        for (var i = 0; i < assemblyNames.Count; i++)
        {
            var candidate = shortNames.Count(name => name == shortNames[i]) == 1
                ? shortNames[i]
                : Identifier(string.Concat(assemblyNames[i].Split('.'))) + "Client";

            var unique = candidate;
            for (var counter = 2; !taken.Add(unique); counter++)
                unique = candidate + counter;

            result.Add(unique);
        }

        return result;
    }

    public static string ClientSource(ClientServer server, string className, bool emitGlobalUsing)
    {
        using var buffer = new StringWriter();
        using var writer = new IndentedTextWriter(buffer);

        writer.WriteLine(Header);
        if (emitGlobalUsing)
        {
            // The call site needs no import, as for the mapping file's own global using.
            writer.WriteLine($"global using global::{Namespace};");
        }

        writer.WriteLine();
        writer.WriteLine("#nullable enable");
        writer.WriteLine("#pragma warning disable CS1591");
        writer.WriteLine();

        writer.WriteLine($"namespace {Namespace}");
        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// A typed client for the endpoints of <c>{Xml(server.AssemblyName)}</c>, generated from the endpoint");
        writer.WriteLine("/// contracts in that assembly's metadata. Each method builds the URL exactly as the server's own");
        writer.WriteLine("/// typed links do, sends the body as JSON, and reads a declared response type from JSON.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("/// <remarks>");
        writer.WriteLine("/// A method with a declared response type throws <see cref=\"global::System.Net.Http.HttpRequestException\"/> for");
        writer.WriteLine("/// a non-success status and returns <see langword=\"default\"/> for 204. A method without one returns the");
        writer.WriteLine("/// <see cref=\"global::System.Net.Http.HttpResponseMessage\"/> unchecked; the caller disposes it. Internal because");
        writer.WriteLine("/// every client project generates its own. Route templates start with '/', so they resolve against the");
        writer.WriteLine("/// root of <see cref=\"global::System.Net.Http.HttpClient.BaseAddress\"/>.");
        writer.WriteLine("/// </remarks>");
        writer.WriteLine($"internal sealed partial class {className}");
        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("private readonly global::System.Net.Http.HttpClient httpClient;");
        writer.WriteLine("private readonly global::System.Text.Json.JsonSerializerOptions? jsonOptions;");
        writer.WriteLine();
        writer.WriteLine($"/// <summary>Creates the client over <paramref name=\"httpClient\"/>, whose <c>BaseAddress</c> is the server.</summary>");
        writer.WriteLine("/// <param name=\"httpClient\">The client that sends every request.</param>");
        writer.WriteLine("/// <param name=\"jsonOptions\">Serializer options for bodies; null uses the web defaults, as the server does.</param>");
        writer.WriteLine($"public {className}(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions? jsonOptions = null)");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("this.httpClient = httpClient ?? throw new global::System.ArgumentNullException(nameof(httpClient));");
        writer.WriteLine("this.jsonOptions = jsonOptions;");
        writer.Indent--;
        writer.WriteLine("}");

        var methodNames = new HashSet<string>(StringComparer.Ordinal) { className, "httpClient", "jsonOptions" };
        foreach (var endpoint in server.Endpoints)
        {
            foreach (var method in endpoint.Methods)
            {
                // One method per verb for a multi-verb endpoint, suffixed as its OpenAPI operationIds
                // are (PreflightEndpointHead).
                var baseName = Identifier(endpoint.Name + (endpoint.Methods.Length > 1 ? Pascal(method) : "")) + "Async";
                var name = baseName;
                for (var counter = 2; !methodNames.Add(name); counter++)
                    name = baseName + counter;

                writer.WriteLine();
                WriteMethod(writer, endpoint, method, name);
            }
        }

        writer.Indent--;
        writer.WriteLine("}");
        writer.Indent--;
        writer.WriteLine("}");

        writer.Flush();
        return buffer.ToString();
    }

    private static void WriteMethod(IndentedTextWriter writer, ClientEndpoint endpoint, string httpMethod, string methodName)
    {
        // Locals and the fixed parameters are claimed first, so a route token called "body" or
        // "__url" is renamed instead of shadowing them.
        var taken = new HashSet<string>(StringComparer.Ordinal) { "__values", "__url", "__request", "__response", "body", "cancellationToken" };

        var parameters = new List<(string Identifier, string Type, bool IsOptional, string? Key)>();
        foreach (var parameter in endpoint.RouteParameters)
            parameters.Add((Claim(parameter.Key, taken), parameter.IsOptional ? parameter.TypeFqn + "?" : parameter.TypeFqn, parameter.IsOptional, parameter.Key));
        if (endpoint.RequestTypeFqn is not null)
            parameters.Add(("body", endpoint.RequestTypeFqn, false, null));
        foreach (var parameter in endpoint.QueryParameters)
            parameters.Add((Claim(parameter.Key, taken), parameter.TypeFqn + "?", true, parameter.Key));

        // A parameter gets "= null" only when everything after it is optional too (CS1737); the
        // cancellation token always has a default, so it never stops one.
        var declarations = new List<string>();
        for (var i = 0; i < parameters.Count; i++)
        {
            var hasDefault = true;
            for (var j = i; j < parameters.Count && hasDefault; j++)
                hasDefault = parameters[j].IsOptional;

            declarations.Add(hasDefault
                ? $"{parameters[i].Type} {parameters[i].Identifier} = null"
                : $"{parameters[i].Type} {parameters[i].Identifier}");
        }
        declarations.Add("global::System.Threading.CancellationToken cancellationToken = default");

        var returnType = endpoint.ResponseTypeFqn is null
            ? "global::System.Net.Http.HttpResponseMessage"
            : endpoint.ResponseIsNullableValueType ? endpoint.ResponseTypeFqn : endpoint.ResponseTypeFqn + "?";

        writer.WriteLine($"/// <summary><c>{Xml(httpMethod)} {Xml(endpoint.Template)}</c> — endpoint <c>{Xml(endpoint.Name)}</c>.</summary>");
        writer.WriteLine($"public async global::System.Threading.Tasks.Task<{returnType}> {methodName}({string.Join(", ", declarations)})");
        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine($"var __values = new global::System.Collections.Generic.List<{Pair}>();");
        foreach (var parameter in parameters)
        {
            if (parameter.Key is null) continue;

            var add = $"__values.Add(new {Pair}({Literal(parameter.Key)}, {parameter.Identifier}));";
            writer.WriteLine(parameter.IsOptional ? $"if ({parameter.Identifier} is not null) {add}" : add);
        }

        writer.WriteLine($"var __url = {Binder}.Bind({Literal(endpoint.Template)}, __values)");
        writer.Indent++;
        writer.WriteLine($"?? throw new global::System.InvalidOperationException({Literal($"No URL could be built for endpoint '{endpoint.Name}' ({endpoint.Template}): a required route value is missing or empty.")});");
        writer.Indent--;

        writer.WriteLine($"var __request = new global::System.Net.Http.HttpRequestMessage(new global::System.Net.Http.HttpMethod({Literal(httpMethod)}), __url);");
        writer.WriteLine("try");
        writer.WriteLine("{");
        writer.Indent++;

        if (endpoint.RequestTypeFqn is not null)
            writer.WriteLine($"__request.Content = global::System.Net.Http.Json.JsonContent.Create<{endpoint.RequestTypeFqn}>(body, (global::System.Net.Http.Headers.MediaTypeHeaderValue?)null, this.jsonOptions);");

        writer.WriteLine("var __response = await this.httpClient.SendAsync(__request, cancellationToken).ConfigureAwait(false);");

        if (endpoint.ResponseTypeFqn is null)
        {
            writer.WriteLine("return __response;");
        }
        else
        {
            writer.WriteLine("try");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("__response.EnsureSuccessStatusCode();");
            writer.WriteLine("if (__response.StatusCode == global::System.Net.HttpStatusCode.NoContent) return default;");
            writer.WriteLine($"return await global::System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsync<{endpoint.ResponseTypeFqn}>(__response.Content, this.jsonOptions, cancellationToken).ConfigureAwait(false);");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine("finally");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("__response.Dispose();");
            writer.Indent--;
            writer.WriteLine("}");
        }

        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLine("finally");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("__request.Dispose();");
        writer.Indent--;
        writer.WriteLine("}");

        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>A unique, keyword-escaped camelCase identifier for a route or query key.</summary>
    private static string Claim(string key, HashSet<string> taken)
    {
        var name = Identifier(key);
        if (char.IsUpper(name[0])) name = char.ToLowerInvariant(name[0]) + name.Substring(1);

        var candidate = name;
        for (var counter = 2; !taken.Add(candidate); counter++)
            candidate = name + counter;

        return SyntaxFacts.GetKeywordKind(candidate) == SyntaxKind.None ? candidate : "@" + candidate;
    }

    /// <summary>Invalid characters become <c>_</c>; a leading digit gets a <c>_</c> prefix.</summary>
    private static string Identifier(string text)
    {
        var chars = text.Select(c => char.IsLetterOrDigit(c) || c == '_' ? c : '_').ToArray();
        var name = new string(chars);
        if (name.Length == 0 || !SyntaxFacts.IsIdentifierStartCharacter(name[0])) name = "_" + name;
        return name;
    }

    private static string LastSegment(string assemblyName)
    {
        var segments = assemblyName.Split('.').Where(segment => segment.Length > 0).ToArray();
        return segments.Length == 0 ? assemblyName : segments[segments.Length - 1];
    }

    /// <summary><c>OPTIONS</c> → <c>Options</c>.</summary>
    private static string Pascal(string method) =>
        method.Length == 0 ? method : char.ToUpperInvariant(method[0]) + method.Substring(1).ToLowerInvariant();

    private static string Xml(string text) =>
        text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    private static string Literal(string value) =>
        "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", "\\r").Replace("\n", "\\n") + "\"";
}
