using System.CodeDom.Compiler;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using MintPlayer.SourceGenerators.Tools;

namespace MintPlayer.AspNetCore.Endpoints.Generator;

partial class EndpointGenerator
{
    internal static class EndpointMappingProducer
    {
        public const string FileName = "EndpointMapping.g.cs";

        /// <summary>
        /// The namespace the mapping extensions class is emitted into.
        /// </summary>
        /// <remarks>
        /// Not the library's own namespace. The class name is derived from the assembly name or from
        /// <c>[assembly: EndpointsMethodName]</c>, so emitting into
        /// <c>MintPlayer.AspNetCore.Endpoints</c> lets a perfectly reasonable choice — say
        /// <c>MapEndpointRouteBuilder</c> — collide with a type the runtime package ships. Source
        /// beats metadata for a name, so the collision is not even an error: the generated class
        /// silently shadows the shipped one. A namespace only this generator writes to defines that
        /// away, and the emitted <c>global using</c> keeps the call site unchanged.
        /// </remarks>
        private const string GeneratedNamespace = "MintPlayer.AspNetCore.Endpoints.Generated";

        public static void Emit(SourceProductionContext context, EndpointModel model)
        {
            var plan = EndpointMappingPlan.From(model);

            using var buffer = new StringWriter();
            using var writer = new IndentedTextWriter(buffer);

            Write(writer, plan, model.Assembly, context.CancellationToken);

            context.AddSource(FileName, SourceText.From(buffer.ToString(), Encoding.UTF8));
        }

        private static void Write(IndentedTextWriter writer, EndpointMappingPlan plan, AssemblyInfo assembly, CancellationToken cancellationToken)
        {
            var methodName = assembly.GetMethodName();
            var className = assembly.GetSafeClassName();

            writer.WriteLine(Producer.Header);

            // The call site keeps working without the consumer importing anything new.
            writer.WriteLine($"global using global::{GeneratedNamespace};");
            writer.WriteLine();

            // No using directives, deliberately. Every type is global::-qualified AND every
            // extension method is invoked in static form — EndpointRouteBuilderExtensions
            // .MapMethods(routes, …) rather than routes.MapMethods(…) — because an extension
            // *invocation* needs the declaring namespace in scope while a static call does not.
            //
            // A using here would put the consumer's import set on this file's critical path. A
            // project with ImplicitUsings off, or one that declares its own MapMethods on
            // IEndpointRouteBuilder, or one whose namespace shadows Microsoft.AspNetCore.Builder,
            // would fail to compile a file it cannot edit.
            writer.WriteLine("#nullable enable");

            // CS1591 is a COMPILER diagnostic, so the <auto-generated> header above does not
            // suppress it — that exclusion covers analyzers only. Without this, any consumer
            // following this repo's own convention (GenerateDocumentationFile in Release) plus
            // TreatWarningsAsErrors gets errors inside generated code. The public members below
            // also carry real doc comments; this pragma is the second line of defence, and it
            // also covers the compiler-generated members of the emitted lambdas.
            writer.WriteLine("#pragma warning disable CS1591");
            writer.WriteLine();

            // --- Task A: Partial class declarations ---
            // Driven by every declared endpoint, not only the mappable ones: an endpoint dropped for
            // an ambiguous group still needs its base class, or the user's `override HandleAsync`
            // fails with a CS0115 that says nothing about groups.
            foreach (var endpoint in plan.DeclaredEndpoints)
            {
                cancellationToken.ThrowIfCancellationRequested();
                EmitPartial(writer, endpoint);
            }

            // --- Task B: Mapping extension ---
            using (writer.OpenBlock($"namespace {GeneratedNamespace}"))
            using (writer.OpenBlock($"public static class {className}"))
            {
                for (var i = 0; i < plan.MappableEndpoints.Count; i++)
                {
                    var fqn = plan.MappableEndpoints[i].FullyQualifiedName;
                    writer.WriteLine($"private static readonly global::Microsoft.Extensions.DependencyInjection.ObjectFactory<{fqn}> _f{i} =");
                    writer.IndentSingleLine($"global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateFactory<{fqn}>(global::System.Type.EmptyTypes);");
                    writer.WriteLine();
                }

                using (writer.OpenBlock($"public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder {methodName}(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)"))
                {
                    foreach (var endpoint in plan.MappableEndpoints.Where(e => e.GroupTypeFqn is null))
                        EmitEndpointMapping(writer, endpoint, plan, "app");

                    var groupCounter = 0;
                    var emitted = new HashSet<string>(StringComparer.Ordinal);
                    foreach (var rootGroupFqn in plan.RootGroups)
                        EmitGroupTree(writer, rootGroupFqn, "app", ref groupCounter, plan, emitted);

                    writer.WriteLine("return app;");
                }

                writer.WriteLine();
                EmitHelpers(writer);

                writer.WriteLine("public static global::System.Collections.Generic.IReadOnlyList<global::MintPlayer.AspNetCore.Endpoints.EndpointDescriptor> Endpoints { get; } =");
                writer.WriteLine("[");
                writer.Indent++;
                foreach (var endpoint in plan.MappableEndpoints)
                {
                    var prefix = string.Join(
                        " + ",
                        plan.GroupChains[endpoint.FullyQualifiedName].Select(group => $"Prefix<{group}>()"));

                    writer.WriteLine(prefix.Length == 0
                        ? $"Describe<{endpoint.FullyQualifiedName}>({Literal(endpoint.EffectiveDescriptorName)}, \"\"),"
                        : $"Describe<{endpoint.FullyQualifiedName}>({Literal(endpoint.EffectiveDescriptorName)}, {prefix}),");
                }
                writer.Indent--;
                writer.WriteLine("];");
            }
        }

        /// <summary>
        /// Emits the <c>MapGroup</c> call for one group and recurses into its children.
        /// </summary>
        /// <remarks>
        /// <paramref name="emitted"/> bounds the recursion. A cycle is already filtered out of the
        /// plan before it gets here, so this is belt and braces — but it is the one place in the
        /// generator that could otherwise take the whole compiler down with an uncatchable
        /// StackOverflowException, which no test can survive either.
        /// </remarks>
        private static void EmitGroupTree(
            IndentedTextWriter writer,
            string groupFqn,
            string parentVar,
            ref int groupCounter,
            EndpointMappingPlan plan,
            HashSet<string> emitted)
        {
            if (!emitted.Add(groupFqn))
                return;

            var varName = $"grp{groupCounter++}";
            writer.WriteLine();
            using (writer.OpenBlock(""))
            {
                writer.WriteLine($"var {varName} = MapGroup<{groupFqn}>({parentVar});");

                if (plan.EndpointsByGroup.TryGetValue(groupFqn, out var endpoints))
                {
                    foreach (var endpoint in endpoints)
                        EmitEndpointMapping(writer, endpoint, plan, varName);
                }

                if (plan.ChildGroups.TryGetValue(groupFqn, out var children))
                {
                    foreach (var childFqn in children)
                        EmitGroupTree(writer, childFqn, varName, ref groupCounter, plan, emitted);
                }
            }
        }

        /// <summary>
        /// Emits the endpoint's generated partial: its base class and/or its parameter binder.
        /// </summary>
        /// <remarks>
        /// Three shapes, decided by what the endpoint needs and what the consumer already wrote:
        /// <list type="bullet">
        /// <item>
        /// <b>A typed level with no base class of its own</b> gets <c>: {Base}</c>, plus a
        /// <c>BindParameters</c> override if it has bound properties.
        /// </item>
        /// <item>
        /// <b>A typed level whose own base class already reaches a library base</b> gets no base
        /// clause — two partials cannot each name one — and only the override, if there is anything
        /// to bind.
        /// </item>
        /// <item>
        /// <b>A raw endpoint</b> has no library base to override, so it gets an explicit
        /// <c>IParameterBinder</c> implementation which the mapper calls — only when it has bound
        /// properties. A raw endpoint without them still needs no <c>partial</c> and gets nothing.
        /// </item>
        /// </list>
        /// Every shape requires every containing type to be <c>partial</c> too; otherwise emission is
        /// skipped and MPEP019 says why, instead of the consumer reading a CS0260 about a partial
        /// declaration they never wrote.
        /// </remarks>
        private static void EmitPartial(IndentedTextWriter writer, EndpointInfo endpoint)
        {
            if (!endpoint.IsPartial) return;                                // MPEP001 / MPEP014
            if (endpoint.PathSpec is { AllPartial: false }) return;         // MPEP019

            var bindable = endpoint.BoundProperties
                .Where(property => property.Kind != BoundKind.Unsupported && property.IsSettable)
                .ToList();

            string? baseClause;
            if (endpoint.Level == EndpointLevel.Raw)
            {
                if (bindable.Count == 0) return;
                baseClause = " : global::MintPlayer.AspNetCore.Endpoints.IParameterBinder";
            }
            else if (!endpoint.HasExistingBaseClass)
            {
                baseClause = endpoint.GetBaseClassName() is { } baseClass ? $" : {baseClass}" : null;
                if (baseClause is null) return;
            }
            else
            {
                if (!endpoint.BaseChainReachesEndpointBase) return;         // MPEP002
                if (bindable.Count == 0) return;                           // nothing to add
                baseClause = "";
            }

            // OpenPathSpec reopens every containing type, so a nested endpoint emits valid code. A
            // flat namespace block used to produce a file that did not compile.
            using (writer.OpenBlock($"namespace {endpoint.Namespace}"))
            using (writer.OpenPathSpec(endpoint.PathSpec))
            {
                if (bindable.Count == 0)
                {
                    writer.WriteLine($"partial class {endpoint.ClassName}{baseClause} {{ }}");
                }
                else
                {
                    using (writer.OpenBlock($"partial class {endpoint.ClassName}{baseClause}"))
                    {
                        if (endpoint.Level == EndpointLevel.Raw)
                            EmitRawBinder(writer, bindable);
                        else
                            EmitBinderOverride(writer, bindable);
                    }
                }
            }
            writer.WriteLine();
        }

        private static void EmitBinderOverride(IndentedTextWriter writer, List<BoundProperty> properties)
        {
            using (writer.OpenBlock("protected override void BindParameters(global::Microsoft.AspNetCore.Http.HttpContext context)"))
            {
                EmitAssignments(writer, properties);
            }
        }

        private static void EmitRawBinder(IndentedTextWriter writer, List<BoundProperty> properties)
        {
            using (writer.OpenBlock("global::Microsoft.AspNetCore.Http.IResult? global::MintPlayer.AspNetCore.Endpoints.IParameterBinder.BindParameters(global::Microsoft.AspNetCore.Http.HttpContext context)"))
            {
                using (writer.OpenBlock("try"))
                {
                    EmitAssignments(writer, properties);
                    writer.WriteLine("return null;");
                }
                using (writer.OpenBlock("catch (global::MintPlayer.AspNetCore.Endpoints.EndpointBindingException failure)"))
                {
                    writer.WriteLine("return global::MintPlayer.AspNetCore.Endpoints.ParameterBinding.Failure(failure);");
                }
            }
        }

        /// <summary>
        /// One statement per property. A property with an initializer keeps that value unless the
        /// request supplies one, so it gets the <c>Try…</c> form; a nullable one binds absent to
        /// null; anything else is required.
        /// </summary>
        private static void EmitAssignments(IndentedTextWriter writer, List<BoundProperty> properties)
        {
            const string Binding = "global::MintPlayer.AspNetCore.Endpoints.ParameterBinding";

            for (var i = 0; i < properties.Count; i++)
            {
                var property = properties[i];
                var source = property.Source == BoundSource.Route
                    ? "global::MintPlayer.AspNetCore.Endpoints.ParameterSource.Route"
                    : "global::MintPlayer.AspNetCore.Endpoints.ParameterSource.Query";
                var key = Literal(property.Key);
                var type = property.ConversionTypeFqn;

                var family = property.Kind switch
                {
                    BoundKind.String => ("String", "OptionalString", "TryString", false),
                    BoundKind.Enum => ("Enum", "OptionalEnum", "TryEnum", true),
                    BoundKind.ParsableReference => ("Parsable", "OptionalParsableReference", "TryParsable", true),
                    _ => ("Parsable", "OptionalParsable", "TryParsable", true),
                };
                var generic = family.Item4 ? $"<{type}>" : "";

                if (property.HasInitializer)
                    writer.WriteLine($"if ({Binding}.{family.Item3}{generic}(context, {source}, {key}, out var __v{i})) this.{property.Name} = __v{i};");
                else if (property.IsOptional)
                    writer.WriteLine($"this.{property.Name} = {Binding}.{family.Item2}{generic}(context, {source}, {key});");
                else
                    writer.WriteLine($"this.{property.Name} = {Binding}.{family.Item1}{generic}(context, {source}, {key});");
            }
        }

        private static void EmitEndpointMapping(IndentedTextWriter writer, EndpointInfo endpoint, EndpointMappingPlan plan, string routesVar)
        {
            var factoryField = $"_f{plan.FactoryIndex[endpoint.FullyQualifiedName]}";

            if (endpoint.Level == EndpointLevel.TypedWithResponse)
            {
                using (writer.OpenBlock(""))
                {
                    writer.WriteLine($"var b = Map<{endpoint.FullyQualifiedName}>({routesVar}, {factoryField});");
                    writer.WriteLine($"Produces<{endpoint.FullyQualifiedName}, {endpoint.RequestTypeFqn}, {endpoint.ResponseTypeFqn}>(b);");
                }
            }
            else if (endpoint.Level == EndpointLevel.ResponseOnly)
            {
                using (writer.OpenBlock(""))
                {
                    writer.WriteLine($"var b = Map<{endpoint.FullyQualifiedName}>({routesVar}, {factoryField});");
                    writer.WriteLine($"ProducesResponse<{endpoint.FullyQualifiedName}, {endpoint.ResponseTypeFqn}>(b);");
                }
            }
            else
            {
                writer.WriteLine($"Map<{endpoint.FullyQualifiedName}>({routesVar}, {factoryField});");
            }
        }

        private static void EmitHelpers(IndentedTextWriter writer)
        {
            using (writer.OpenBlock("private static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder Map<TEndpoint>(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder routes, global::Microsoft.Extensions.DependencyInjection.ObjectFactory<TEndpoint> factory) where TEndpoint : class, global::MintPlayer.AspNetCore.Endpoints.IEndpoint"))
            {
                using (writer.OpenBlock("var builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapMethods(routes, TEndpoint.Path, TEndpoint.Methods, async (global::Microsoft.AspNetCore.Http.HttpContext ctx) =>"))
                {
                    // Constructed INSIDE the delegate, per request. Bound properties make an endpoint
                    // stateful; hoisting this out of the lambda would turn it into a process-wide
                    // singleton that leaks one request's route values into the next (PRD R2.12).
                    writer.WriteLine("var ep = factory(ctx.RequestServices, null);");
                    using (writer.OpenBlock("try"))
                    {
                        // Raw endpoints only: every other level binds inside its own HandleAsync.
                        writer.WriteLine("if (ep is global::MintPlayer.AspNetCore.Endpoints.IParameterBinder binder && binder.BindParameters(ctx) is { } failed) return failed;");
                        writer.WriteLine("return await ep.HandleAsync(ctx);");
                    }
                    using (writer.OpenBlock("finally"))
                    {
                        writer.WriteLine("if (ep is global::System.IAsyncDisposable ad) await ad.DisposeAsync();");
                        writer.WriteLine("else if (ep is global::System.IDisposable d) d.Dispose();");
                    }
                }
                writer.WriteLine(");");
                writer.WriteLine("global::Microsoft.AspNetCore.Builder.RoutingEndpointConventionBuilderExtensions.WithMetadata(builder, global::MintPlayer.AspNetCore.Endpoints.EndpointAttributes.ForMetadata(typeof(TEndpoint)));");
                writer.WriteLine("TEndpoint.Configure(builder);");
                writer.WriteLine("return builder;");
            }
            writer.WriteLine();

            using (writer.OpenBlock("private static global::Microsoft.AspNetCore.Routing.RouteGroupBuilder MapGroup<TGroup>(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder routes) where TGroup : global::MintPlayer.AspNetCore.Endpoints.IEndpointGroup"))
            {
                writer.WriteLine("var group = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGroup(routes, TGroup.Prefix);");
                writer.WriteLine("TGroup.Configure(group);");
                writer.WriteLine("return group;");
            }
            writer.WriteLine();

            using (writer.OpenBlock("private static void Produces<TEndpoint, TRequest, TResponse>(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder) where TEndpoint : global::MintPlayer.AspNetCore.Endpoints.IEndpoint<TRequest, TResponse>"))
            {
                writer.WriteLine("global::Microsoft.AspNetCore.Http.OpenApiRouteHandlerBuilderExtensions.Produces<TResponse>(builder, TEndpoint.SuccessStatusCode);");
            }
            writer.WriteLine();

            using (writer.OpenBlock("private static void ProducesResponse<TEndpoint, TResponse>(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder) where TEndpoint : global::MintPlayer.AspNetCore.Endpoints.IResponseEndpoint<TResponse>"))
            {
                writer.WriteLine("global::Microsoft.AspNetCore.Http.OpenApiRouteHandlerBuilderExtensions.Produces<TResponse>(builder, TEndpoint.SuccessStatusCode);");
            }
            writer.WriteLine();

            using (writer.OpenBlock("private static string Prefix<TGroup>() where TGroup : global::MintPlayer.AspNetCore.Endpoints.IEndpointGroup"))
            {
                writer.WriteLine("return TGroup.Prefix;");
            }
            writer.WriteLine();

            // groupPrefix is baked in by the generator, which is the only component that knows the
            // group chain. TEndpoint.Path on its own is group-relative, so a descriptor built from it
            // describes an endpoint in /api/users as "/{id}" — useless for the diagnostics or
            // discovery page the descriptor list exists for.
            using (writer.OpenBlock("private static global::MintPlayer.AspNetCore.Endpoints.EndpointDescriptor Describe<TEndpoint>(string name, string groupPrefix) where TEndpoint : global::MintPlayer.AspNetCore.Endpoints.IEndpointBase"))
            {
                writer.WriteLine("return new(name, groupPrefix + TEndpoint.Path, [.. TEndpoint.Methods], typeof(TEndpoint));");
            }
            writer.WriteLine();
        }

        private static string Literal(string value) =>
            "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
    }
}
