using System.CodeDom.Compiler;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using MintPlayer.SourceGenerators.Tools;

namespace MintPlayer.AspNetCore.Endpoints.Generator;

partial class EndpointGenerator
{
    /// <summary>
    /// Emits <c>EndpointMapping.g.cs</c>: the endpoints' partial declarations, the
    /// <c>Map…Endpoints()</c> extension, the shadow parameter types and the descriptor list.
    /// </summary>
    /// <remarks>
    /// Compiles identically whether or not the consumer references
    /// <c>Microsoft.AspNetCore.OpenApi</c>; everything that needs that package is in
    /// <see cref="EndpointOpenApiProducer"/>, reached through erasable partial-method hooks.
    /// </remarks>
    internal sealed class EndpointMappingProducer : EndpointsProducer
    {
        public const string FileName = "EndpointMapping.g.cs";

        public EndpointMappingProducer(EndpointModel model) : base(model, FileName) { }

        protected override void ProduceSource(IndentedTextWriter writer, CancellationToken cancellationToken)
        {
            // A typed-client project runs this generator too, and has no ASP.NET Core to map onto.
            if (!Model.Assembly.CanMapEndpoints) return;

            Write(writer, Model.GetPlan(), Model.Assembly, cancellationToken);
        }

        private static void Write(IndentedTextWriter writer, EndpointMappingPlan plan, AssemblyInfo assembly, CancellationToken cancellationToken)
        {
            var methodName = assembly.GetMethodName();
            var className = assembly.GetSafeClassName();

            writer.WriteLine(Header);

            // The call site keeps working without the consumer importing anything new.
            writer.WriteLine($"global using global::{GeneratedNamespace};");
            writer.WriteLine();

            // Issue #34, PRD D3a: this assembly's open-generic endpoints, and the groups they may sit
            // in, recorded for the application that closes them — it sees this assembly as metadata,
            // where a Path's body and the declaring syntax are gone. Assembly attributes must follow
            // the global using and precede every namespace member (CS1730). Nothing is written for an
            // assembly without open endpoints, so its output is unchanged.
            if (assembly.CanRecordOpenEndpoints && EmitOpenEndpointRecords(writer, plan))
                writer.WriteLine();

            // No using directives, deliberately. Every type is global::-qualified AND every
            // extension method is invoked in static form — EndpointRouteBuilderExtensions
            // .MapMethods(routes, …) rather than routes.MapMethods(…) — because an extension
            // *invocation* needs the declaring namespace in scope while a static call does not.
            //
            // A using here would put the consumer's import set on this file's critical path. A
            // project with ImplicitUsings off, or one that declares its own MapMethods on
            // IEndpointRouteBuilder, or one whose namespace shadows Microsoft.AspNetCore.Builder,
            // would fail to compile a file it cannot edit.
            writer.WriteLine("#nullable enable");

            // CS1591 is a COMPILER diagnostic, so the <auto-generated> header above does not
            // suppress it — that exclusion covers analyzers only. Without this, any consumer
            // following this repo's own convention (GenerateDocumentationFile in Release) plus
            // TreatWarningsAsErrors gets errors inside generated code. The public members below
            // also carry real doc comments; this pragma is the second line of defence, and it
            // also covers the compiler-generated members of the emitted lambdas.
            writer.WriteLine("#pragma warning disable CS1591");
            writer.WriteLine();

            // --- Task A: Partial class declarations ---
            // Driven by every declared endpoint, not only the mappable ones: an endpoint dropped for
            // an ambiguous group still needs its base class, or the user's `override HandleAsync`
            // fails with a CS0115 that says nothing about groups.
            foreach (var endpoint in plan.DeclaredEndpoints)
            {
                cancellationToken.ThrowIfCancellationRequested();
                EmitPartial(writer, endpoint);
            }

            var shadows = plan.MappableEndpoints.ToDictionary(
                endpoint => endpoint.FullyQualifiedName,
                endpoint => plan.ShadowParametersOf(endpoint),
                StringComparer.Ordinal);

            // --- Task B: Mapping extension ---
            // Partial so the OpenAPI producer can add to it (EndpointOpenApi.g.cs). This file must
            // not name a single Microsoft.AspNetCore.OpenApi or Microsoft.OpenApi type: it has to
            // compile identically whether or not the consumer references that package.
            using (writer.OpenBlock($"namespace {GeneratedNamespace}"))
            using (writer.OpenBlock($"public static partial class {className}"))
            {
                for (var i = 0; i < plan.MappableEndpoints.Count; i++)
                {
                    var fqn = plan.MappableEndpoints[i].FullyQualifiedName;
                    writer.WriteLine($"private static readonly global::Microsoft.Extensions.DependencyInjection.ObjectFactory<{fqn}> _f{i} =");
                    writer.IndentSingleLine($"global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateFactory<{fqn}>(global::System.Type.EmptyTypes);");
                    writer.WriteLine();
                }

                using (writer.OpenBlock($"public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder {methodName}(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)"))
                {
                    foreach (var endpoint in plan.MappableEndpoints.Where(e => e.GroupTypeFqn is null))
                        EmitEndpointMapping(writer, endpoint, plan, shadows, "app");

                    var groupCounter = 0;
                    var emitted = new HashSet<string>(StringComparer.Ordinal);
                    foreach (var rootGroupFqn in plan.RootGroups)
                        EmitGroupTree(writer, rootGroupFqn, "app", ref groupCounter, plan, shadows, emitted);

                    writer.WriteLine("return app;");
                }

                writer.WriteLine();
                EmitHelpers(writer);
                EmitHooks(writer, plan, shadows);
                EmitShadowTypes(writer, plan, shadows);

                writer.WriteLine("public static global::System.Collections.Generic.IReadOnlyList<global::MintPlayer.AspNetCore.Endpoints.EndpointDescriptor> Endpoints { get; } =");
                writer.WriteLine("[");
                writer.Indent++;
                foreach (var endpoint in plan.MappableEndpoints)
                {
                    var prefix = string.Join(
                        " + ",
                        plan.GroupChains[endpoint.FullyQualifiedName].Select(group => $"Prefix<{group}>()"));

                    writer.WriteLine(prefix.Length == 0
                        ? $"Describe<{endpoint.FullyQualifiedName}>({Literal(endpoint.EffectiveDescriptorName)}, \"\"),"
                        : $"Describe<{endpoint.FullyQualifiedName}>({Literal(endpoint.EffectiveDescriptorName)}, {prefix}),");
                }
                writer.Indent--;
                writer.WriteLine("];");
            }
        }

        /// <summary>
        /// Emits the <c>MapGroup</c> call for one group and recurses into its children.
        /// </summary>
        /// <remarks>
        /// <paramref name="emitted"/> bounds the recursion. A cycle is already filtered out of the
        /// plan before it gets here, so this is belt and braces — but it is the one place in the
        /// generator that could otherwise take the whole compiler down with an uncatchable
        /// StackOverflowException, which no test can survive either.
        /// </remarks>
        private static void EmitGroupTree(
            IndentedTextWriter writer,
            string groupFqn,
            string parentVar,
            ref int groupCounter,
            EndpointMappingPlan plan,
            Dictionary<string, List<ShadowMember>> shadows,
            HashSet<string> emitted)
        {
            if (!emitted.Add(groupFqn))
                return;

            var varName = $"grp{groupCounter++}";
            writer.WriteLine();

            // PRD D5: a group that is not enabled maps nothing, nested groups included, decided once at
            // map time. Through a helper: a static virtual member cannot be called on a class that does
            // not declare it (G.IsEnabled is CS0117 unless G overrides it).
            using (writer.OpenBlock($"if (IsEnabled<{groupFqn}>(app.ServiceProvider))"))
            {
                writer.WriteLine($"var {varName} = MapGroup<{groupFqn}>({parentVar});");

                if (plan.EndpointsByGroup.TryGetValue(groupFqn, out var endpoints))
                {
                    foreach (var endpoint in endpoints)
                        EmitEndpointMapping(writer, endpoint, plan, shadows, varName);
                }

                if (plan.ChildGroups.TryGetValue(groupFqn, out var children))
                {
                    foreach (var childFqn in children)
                        EmitGroupTree(writer, childFqn, varName, ref groupCounter, plan, shadows, emitted);
                }
            }
        }

        /// <summary>
        /// Emits the endpoint's generated partial: its base class and/or its parameter binder.
        /// </summary>
        /// <remarks>
        /// Three shapes, decided by what the endpoint needs and what the consumer already wrote:
        /// <list type="bullet">
        /// <item>
        /// <b>A typed level with no base class of its own</b> gets <c>: {Base}</c>, plus a
        /// <c>BindParameters</c> override if it has bound properties.
        /// </item>
        /// <item>
        /// <b>A typed level whose own base class already reaches a library base</b> gets no base
        /// clause — two partials cannot each name one — and only the override, if there is anything
        /// to bind.
        /// </item>
        /// <item>
        /// <b>A raw endpoint</b> has no library base to override, so it gets an explicit
        /// <c>IParameterBinder</c> implementation which the mapper calls — only when it has bound
        /// properties. A raw endpoint without them still needs no <c>partial</c> and gets nothing.
        /// </item>
        /// </list>
        /// Every shape requires every containing type to be <c>partial</c> too; otherwise emission is
        /// skipped and MPEP019 says why, instead of the consumer reading a CS0260 about a partial
        /// declaration they never wrote.
        /// </remarks>
        private static void EmitPartial(IndentedTextWriter writer, EndpointInfo endpoint)
        {
            if (!endpoint.IsPartial) return;                                // MPEP001 / MPEP014
            if (endpoint.PathSpec is { AllPartial: false }) return;         // MPEP019
            if (endpoint.IsInFileLocalType) return;                         // MPEP024: a partial cannot join a file type

            var bindable = ShadowParameters.Bindable(endpoint);

            string? baseClause;
            if (endpoint.Level == EndpointLevel.Raw)
            {
                if (bindable.Count == 0) return;
                baseClause = " : global::MintPlayer.AspNetCore.Endpoints.IParameterBinder";
            }
            else if (!endpoint.HasExistingBaseClass)
            {
                baseClause = endpoint.GetBaseClassName() is { } baseClass ? $" : {baseClass}" : null;
                if (baseClause is null) return;
            }
            else
            {
                if (!endpoint.BaseChainReachesEndpointBase) return;         // MPEP002
                if (bindable.Count == 0) return;                           // nothing to add
                baseClause = "";
            }

            // OpenPathSpec reopens every containing type, so a nested endpoint emits valid code. A
            // flat namespace block used to produce a file that did not compile. An endpoint in the global
            // namespace gets no namespace block at all: "namespace <global namespace>" is what
            // ToDisplayString() gives for it, and that emitted a file that did not compile either.
            // A generic endpoint's partial repeats its type parameter list (PRD R3): without it the part
            // declares a second, non-generic class of the same name, and the real class never gets its
            // base class or binder. Constraints need not be repeated on a partial part.
            var typeParameters = endpoint.Open?.OwnTypeParameters ?? "";

            using (endpoint.Namespace.Length > 0 ? writer.OpenBlock($"namespace {endpoint.Namespace}") : (IDisposable?)null)
            using (writer.OpenPathSpec(endpoint.PathSpec))
            {
                if (bindable.Count == 0)
                {
                    writer.WriteLine($"partial class {endpoint.ClassName}{typeParameters}{baseClause} {{ }}");
                }
                else
                {
                    using (writer.OpenBlock($"partial class {endpoint.ClassName}{typeParameters}{baseClause}"))
                    {
                        if (endpoint.Level == EndpointLevel.Raw)
                            EmitRawBinder(writer, bindable);
                        else
                            EmitBinderOverride(writer, bindable);
                    }
                }
            }
            writer.WriteLine();
        }

        private static void EmitBinderOverride(IndentedTextWriter writer, List<BoundProperty> properties)
        {
            using (writer.OpenBlock("protected override void BindParameters(global::Microsoft.AspNetCore.Http.HttpContext context)"))
            {
                EmitAssignments(writer, properties);
            }
        }

        private static void EmitRawBinder(IndentedTextWriter writer, List<BoundProperty> properties)
        {
            using (writer.OpenBlock("global::Microsoft.AspNetCore.Http.IResult? global::MintPlayer.AspNetCore.Endpoints.IParameterBinder.BindParameters(global::Microsoft.AspNetCore.Http.HttpContext context)"))
            {
                using (writer.OpenBlock("try"))
                {
                    EmitAssignments(writer, properties);
                    writer.WriteLine("return null;");
                }
                using (writer.OpenBlock("catch (global::MintPlayer.AspNetCore.Endpoints.EndpointBindingException failure)"))
                {
                    writer.WriteLine("return global::MintPlayer.AspNetCore.Endpoints.ParameterBinding.Failure(failure);");
                }
            }
        }

        /// <summary>
        /// One statement per property. A property with an initializer keeps that value unless the
        /// request supplies one, so it gets the <c>Try…</c> form; a nullable one binds absent to
        /// null; anything else is required.
        /// </summary>
        private static void EmitAssignments(IndentedTextWriter writer, List<BoundProperty> properties)
        {
            const string Binding = "global::MintPlayer.AspNetCore.Endpoints.ParameterBinding";

            for (var i = 0; i < properties.Count; i++)
            {
                var property = properties[i];
                var source = property.Source == BoundSource.Route
                    ? "global::MintPlayer.AspNetCore.Endpoints.ParameterSource.Route"
                    : "global::MintPlayer.AspNetCore.Endpoints.ParameterSource.Query";
                var key = Literal(property.Key);
                var type = property.ConversionTypeFqn;

                var family = property.Kind switch
                {
                    BoundKind.String => ("String", "OptionalString", "TryString", false),
                    BoundKind.Enum => ("Enum", "OptionalEnum", "TryEnum", true),
                    BoundKind.ParsableReference => ("Parsable", "OptionalParsableReference", "TryParsable", true),
                    _ => ("Parsable", "OptionalParsable", "TryParsable", true),
                };
                var generic = family.Item4 ? $"<{type}>" : "";

                if (property.HasInitializer)
                    writer.WriteLine($"if ({Binding}.{family.Item3}{generic}(context, {source}, {key}, out var __v{i})) this.{property.Name} = __v{i};");
                else if (property.IsOptional)
                    writer.WriteLine($"this.{property.Name} = {Binding}.{family.Item2}{generic}(context, {source}, {key});");
                else
                    writer.WriteLine($"this.{property.Name} = {Binding}.{family.Item1}{generic}(context, {source}, {key});");
            }
        }

        private static void EmitEndpointMapping(
            IndentedTextWriter writer,
            EndpointInfo endpoint,
            EndpointMappingPlan plan,
            Dictionary<string, List<ShadowMember>> shadows,
            string routesVar)
        {
            const string Documentation = "global::MintPlayer.AspNetCore.Endpoints.EndpointDocumentation";

            var index = plan.FactoryIndex[endpoint.FullyQualifiedName];
            var factoryField = $"_f{index}";
            var shadow = shadows[endpoint.FullyQualifiedName];

            var map = shadow.Count == 0
                ? $"Map<{endpoint.FullyQualifiedName}>({routesVar}, {factoryField})"
                : $"Map<{endpoint.FullyQualifiedName}, {ShadowParameters.TypeName(endpoint, index)}>({routesVar}, {factoryField})";

            var statements = new List<string>();

            if (endpoint.Level == EndpointLevel.TypedWithResponse)
                statements.Add($"Produces<{endpoint.FullyQualifiedName}, {endpoint.RequestTypeFqn}, {endpoint.ResponseTypeFqn}>(b);");
            else if (endpoint.Level == EndpointLevel.ResponseOnly)
                statements.Add($"ProducesResponse<{endpoint.FullyQualifiedName}, {endpoint.ResponseTypeFqn}>(b);");

            // A request body can fail to bind (400) or arrive in a type nothing reads (415); a bound
            // property can only fail to bind. Both are declared through the runtime helper the manual
            // MapEndpoint<T>() path calls too, so the two registrations cannot drift apart.
            if (endpoint.Level is EndpointLevel.Typed or EndpointLevel.TypedWithResponse)
                statements.Add($"{Documentation}.DeclareRequestBody(b, typeof({endpoint.RequestTypeFqn}));");
            else if (ShadowParameters.Bound(endpoint).Count > 0)
                statements.Add($"{Documentation}.DeclareBindingFailure(b);");

            // Erased by the compiler unless EndpointOpenApi.g.cs implements it.
            if (shadow.Any(member => member.HasTypedSchema))
                statements.Add($"{ShadowParameters.HookName(index)}(b);");

            // One name, three uses: the route name the typed links in EndpointRoutes.g.cs generate
            // from, the OpenAPI operationId, and the link method's name. Applied after the endpoint's
            // own Configure (which runs inside Map), so the name the links rely on is the one that
            // sticks. An MPEP012 duplicate gets none — see EndpointMappingPlan.DuplicateNames.
            if (plan.IsNamed(endpoint))
            {
                statements.Add($"global::Microsoft.AspNetCore.Builder.RoutingEndpointConventionBuilderExtensions.WithName(b, {Literal(endpoint.EffectiveDescriptorName)});");

                // Erased unless EndpointOpenApi.g.cs implements it: one name on several verbs would be
                // one operationId on several operations, which OpenAPI forbids.
                if (TypedLinkHooks.NeedsOperationIdPerMethod(endpoint))
                    statements.Add($"{TypedLinkHooks.HookName(index)}(b);");
            }

            if (statements.Count == 0)
            {
                writer.WriteLine($"{map};");
                return;
            }

            using (writer.OpenBlock(""))
            {
                writer.WriteLine($"var b = {map};");
                foreach (var statement in statements)
                    writer.WriteLine(statement);
            }
        }

        private static void EmitHelpers(IndentedTextWriter writer)
        {
            using (writer.OpenBlock("private static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder Map<TEndpoint>(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder routes, global::Microsoft.Extensions.DependencyInjection.ObjectFactory<TEndpoint> factory) where TEndpoint : class, global::MintPlayer.AspNetCore.Endpoints.IEndpoint"))
            {
                EmitMapBody(writer, "global::Microsoft.AspNetCore.Http.HttpContext ctx");
            }
            writer.WriteLine();

            // The shadow rides in as a generic type argument rather than a per-endpoint lambda, which
            // is only sound because ApiExplorer reads the *closed* delegate at run time: measured on
            // net10.0 and net11.0, an [AsParameters] TShadow here documents exactly the parameters a
            // lambda spelling out the concrete type does. (Source-generated consumers such as
            // Microsoft.Extensions.Validation read the open lambda at compile time and do not see
            // through a type parameter — nothing here relies on them seeing the shadow.)
            using (writer.OpenBlock("private static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder Map<TEndpoint, TShadow>(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder routes, global::Microsoft.Extensions.DependencyInjection.ObjectFactory<TEndpoint> factory) where TEndpoint : class, global::MintPlayer.AspNetCore.Endpoints.IEndpoint where TShadow : class"))
            {
                // __shadow is bound by the framework and never read. Every member is a string?, so
                // binding it cannot fail and the library's own binder below still produces the 400.
                EmitMapBody(writer, "[global::Microsoft.AspNetCore.Http.AsParametersAttribute] TShadow __shadow, global::Microsoft.AspNetCore.Http.HttpContext ctx");
            }
            writer.WriteLine();

            using (writer.OpenBlock("private static global::Microsoft.AspNetCore.Routing.RouteGroupBuilder MapGroup<TGroup>(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder routes) where TGroup : global::MintPlayer.AspNetCore.Endpoints.IEndpointGroup"))
            {
                writer.WriteLine("var group = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGroup(routes, TGroup.Prefix);");
                writer.WriteLine("TGroup.Configure(group);");
                writer.WriteLine("return group;");
            }
            writer.WriteLine();

            using (writer.OpenBlock("private static void Produces<TEndpoint, TRequest, TResponse>(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder) where TEndpoint : global::MintPlayer.AspNetCore.Endpoints.IEndpoint<TRequest, TResponse>"))
            {
                writer.WriteLine("global::Microsoft.AspNetCore.Http.OpenApiRouteHandlerBuilderExtensions.Produces<TResponse>(builder, TEndpoint.SuccessStatusCode);");
            }
            writer.WriteLine();

            using (writer.OpenBlock("private static void ProducesResponse<TEndpoint, TResponse>(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder) where TEndpoint : global::MintPlayer.AspNetCore.Endpoints.IResponseEndpoint<TResponse>"))
            {
                writer.WriteLine("global::Microsoft.AspNetCore.Http.OpenApiRouteHandlerBuilderExtensions.Produces<TResponse>(builder, TEndpoint.SuccessStatusCode);");
            }
            writer.WriteLine();

            using (writer.OpenBlock("private static string Prefix<TGroup>() where TGroup : global::MintPlayer.AspNetCore.Endpoints.IEndpointGroup"))
            {
                writer.WriteLine("return TGroup.Prefix;");
            }
            writer.WriteLine();

            using (writer.OpenBlock("private static bool IsEnabled<TGroup>(global::System.IServiceProvider services) where TGroup : global::MintPlayer.AspNetCore.Endpoints.IEndpointGroup"))
            {
                writer.WriteLine("return TGroup.IsEnabled(services);");
            }
            writer.WriteLine();

            // groupPrefix is baked in by the generator, which is the only component that knows the
            // group chain. TEndpoint.Path on its own is group-relative, so a descriptor built from it
            // describes an endpoint in /api/users as "/{id}" — useless for the diagnostics or
            // discovery page the descriptor list exists for.
            using (writer.OpenBlock("private static global::MintPlayer.AspNetCore.Endpoints.EndpointDescriptor Describe<TEndpoint>(string name, string groupPrefix) where TEndpoint : global::MintPlayer.AspNetCore.Endpoints.IEndpointBase"))
            {
                writer.WriteLine("return new(name, groupPrefix + TEndpoint.Path, [.. TEndpoint.Methods], typeof(TEndpoint));");
            }
            writer.WriteLine();
        }

        /// <summary>
        /// The body shared by both <c>Map</c> helpers; only the request delegate's parameter list differs.
        /// </summary>
        /// <remarks>
        /// Emitted inline in each helper rather than factored into a shared method the lambda calls:
        /// the construction has to be visibly inside the delegate (R2.12), and a test pins it there by
        /// position in each helper.
        /// </remarks>
        private static void EmitMapBody(IndentedTextWriter writer, string delegateParameters)
        {
            using (writer.OpenBlock($"var builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapMethods(routes, TEndpoint.Path, TEndpoint.Methods, async ({delegateParameters}) =>"))
            {
                // Constructed INSIDE the delegate, per request. Bound properties make an endpoint
                // stateful; hoisting this out of the lambda would turn it into a process-wide
                // singleton that leaks one request's route values into the next (PRD R2.12).
                writer.WriteLine("var ep = factory(ctx.RequestServices, null);");
                using (writer.OpenBlock("try"))
                {
                    // Raw endpoints only: every other level binds inside its own HandleAsync.
                    writer.WriteLine("if (ep is global::MintPlayer.AspNetCore.Endpoints.IParameterBinder binder && binder.BindParameters(ctx) is { } failed) return failed;");
                    writer.WriteLine("return await ep.HandleAsync(ctx);");
                }
                using (writer.OpenBlock("finally"))
                {
                    writer.WriteLine("if (ep is global::System.IAsyncDisposable ad) await ad.DisposeAsync();");
                    writer.WriteLine("else if (ep is global::System.IDisposable d) d.Dispose();");
                }
            }
            writer.WriteLine(");");
            writer.WriteLine("global::Microsoft.AspNetCore.Builder.RoutingEndpointConventionBuilderExtensions.WithMetadata(builder, global::MintPlayer.AspNetCore.Endpoints.EndpointAttributes.ForMetadata(typeof(TEndpoint)));");
            writer.WriteLine("TEndpoint.Configure(builder);");
            writer.WriteLine("return builder;");
        }

        /// <summary>
        /// Declares one partial-method hook per endpoint whose shadow has a typed schema to restore.
        /// </summary>
        /// <remarks>
        /// This is the whole seam between this file and <c>EndpointOpenApi.g.cs</c>. A partial method
        /// that returns <c>void</c> and has no access modifier may be left unimplemented, and then the
        /// compiler removes the declaration <i>and every call to it</i> — so a consumer without
        /// <c>Microsoft.AspNetCore.OpenApi</c> gets no method, no call and no reference, and this file
        /// never has to name an OpenAPI type to make the call. One hook per endpoint rather than one
        /// generic hook, so the implementing file dispatches at compile time instead of testing
        /// <c>typeof(TEndpoint)</c> against every endpoint.
        /// </remarks>
        private static void EmitHooks(IndentedTextWriter writer, EndpointMappingPlan plan, Dictionary<string, List<ShadowMember>> shadows)
        {
            var any = false;
            foreach (var endpoint in plan.MappableEndpoints)
            {
                if (!shadows[endpoint.FullyQualifiedName].Any(member => member.HasTypedSchema)) continue;

                writer.WriteLine($"static partial void {ShadowParameters.HookName(plan.FactoryIndex[endpoint.FullyQualifiedName])}(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder);");
                any = true;
            }

            foreach (var endpoint in plan.MappableEndpoints)
            {
                if (!plan.IsNamed(endpoint) || !TypedLinkHooks.NeedsOperationIdPerMethod(endpoint)) continue;

                writer.WriteLine($"static partial void {TypedLinkHooks.HookName(plan.FactoryIndex[endpoint.FullyQualifiedName])}(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder);");
                any = true;
            }

            if (any) writer.WriteLine();
        }

        /// <summary>Emits the <c>string?</c> shadow parameter type of every endpoint that has one.</summary>
        private static void EmitShadowTypes(IndentedTextWriter writer, EndpointMappingPlan plan, Dictionary<string, List<ShadowMember>> shadows)
        {
            foreach (var endpoint in plan.MappableEndpoints)
            {
                var members = shadows[endpoint.FullyQualifiedName];
                if (members.Count == 0) continue;

                var typeName = ShadowParameters.TypeName(endpoint, plan.FactoryIndex[endpoint.FullyQualifiedName]);

                writer.WriteLine($"/// <summary>The route and query parameters of <c>{endpoint.FullyQualifiedName.Replace("global::", "")}</c>, declared for ApiExplorer only.</summary>");
                writer.WriteLine("/// <remarks>Bound by the framework and never read: every member is a string, so it cannot fail, and the endpoint's own binder does the real conversion.</remarks>");
                using (writer.OpenBlock($"internal sealed class {typeName}"))
                {
                    foreach (var member in members)
                    {
                        var attribute = member.Source == BoundSource.Route
                            ? "global::Microsoft.AspNetCore.Mvc.FromRouteAttribute"
                            : "global::Microsoft.AspNetCore.Mvc.FromQueryAttribute";
                        if (member.NameOverride is not null)
                            attribute += $"(Name = {Literal(member.NameOverride)})";

                        writer.WriteLine($"[{attribute}] public string? @{member.Identifier} {{ get; set; }}");
                    }
                }
                writer.WriteLine();
            }
        }

        /// <summary>
        /// Writes one <c>[assembly: OpenEndpoint(…)]</c> per nameable open endpoint and, when there is
        /// any, one <c>[assembly: OpenEndpointGroup(…)]</c> per nameable declared group (PRD D3a).
        /// </summary>
        /// <remarks>
        /// Every declared group is recorded, not only those on an open endpoint's chain: a chain can pass
        /// through a construction (<c>Api&lt;string&gt;</c>) whose declaration is the open <c>Api&lt;T&gt;</c>,
        /// and the application looks prefixes up by definition. A group record costs one attribute.
        /// </remarks>
        private static bool EmitOpenEndpointRecords(IndentedTextWriter writer, EndpointMappingPlan plan)
        {
            var endpoints = plan.RecordableOpenEndpoints.ToList();
            if (endpoints.Count == 0) return false;

            foreach (var endpoint in endpoints)
            {
                var arguments = new List<string> { $"typeof({endpoint.Open!.UnboundTypeOf})" };
                if (endpoint.Route is not null) arguments.Add($"Path = {Literal(endpoint.Route)}");
                if (endpoint.KnownMethods is not null) arguments.Add($"Methods = {Literal(endpoint.KnownMethods)}");
                if (ShadowParameters.EmitsBinder(endpoint)) arguments.Add("HasBinder = true");
                arguments.Add($"Version = {OpenEndpointRecords.Version}");

                writer.WriteLine($"[assembly: global::{OpenEndpointRecords.AttributeNamespace}.{OpenEndpointRecords.EndpointAttributeName}({string.Join(", ", arguments)})]");
            }

            foreach (var group in plan.DeclaredGroups)
            {
                if (group.InaccessibleReason is not null || group.UnboundTypeOf is null) continue;

                writer.WriteLine(group.Prefix is null
                    ? $"[assembly: global::{OpenEndpointRecords.AttributeNamespace}.{OpenEndpointRecords.GroupAttributeName}(typeof({group.UnboundTypeOf}))]"
                    : $"[assembly: global::{OpenEndpointRecords.AttributeNamespace}.{OpenEndpointRecords.GroupAttributeName}(typeof({group.UnboundTypeOf}), Prefix = {Literal(group.Prefix)})]");
            }

            return true;
        }

        private static string Literal(string value) =>
            "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
    }
}
