name: dotnet-release

on:
  pull_request:
    branches:
      - master
    types: ["closed"]

jobs:
  cherry_pick:

    strategy:
      matrix:
        version: [
          { major: 6, sdk: "6.0.301" }
        ]

    name: cherry-pick
    runs-on: ubuntu-latest
    # Only cherry-pick to release if there's a specified label
    #if: ${{ contains(github.event.pull_request.labels.*.name, format('dotnet-{0}', matrix.version.major)) && github.event.pull_request.merged == true }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Create release/dotnet-${{ matrix.version.major }} branch
      uses: peterjgrainger/action-create-branch@v2.2.0
      if: ${{ contains(github.event.pull_request.labels.*.name, format('dotnet-{0}', matrix.version.major)) && github.event.pull_request.merged == true }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: release/dotnet-${{ matrix.version.major }}
        
    - name: Cherry pick into release/dotnet-${{ matrix.version.major }}
      uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
      if: ${{ contains(github.event.pull_request.labels.*.name, format('dotnet-{0}', matrix.version.major)) && github.event.pull_request.merged == true }}
      with:
        branch: release/dotnet-${{ matrix.version.major }}
        labels: |
          cherry-pick
        title: '[cherry-pick] #{old_title}'
        body: 'Cherry picking #{old_pull_request_id} onto release/dotnet-#{matrix.version.major}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      